apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gnindex-api
  namespace: gn
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  backend:
    serviceName: gnindex-api
    servicePort: 80
  rules:
  - host: mini
    http:
      paths:
      - path: /
        backend:
          serviceName: gnindex-api
          servicePort: 8888
