---
apiVersion: v1
kind: Service
metadata:
  name: gnindex-api
  namespace: gn
  labels:
    app: gnindex
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8888
      name: thrift-api
      targetPort: 8888
    - port: 9990
      name: http-admin
      targetPort: 9990
  selector:
    app: gnindex
    tier: frontend
    type: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnindex-api
  namespace: gn
spec:
  replicas: 1
  template:
    metadata:
      name: gnindex-api
      labels:
        app: gnindex
        tier: frontend
        type: api
    spec:
      containers:
        - name: gnindex
          image: gnames/gnindex-debug:gnindexapi-0.1.0-20170827_0751_CDT-SNAPSHOT
          readinessProbe:
            httpGet:
              path: /admin/ping
              port: 9990
            initialDelaySeconds: 30
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /admin/ping
              port: 9990
            initialDelaySeconds: 300
            timeoutSeconds: 3
          env:
            - name: NAMERESOLVER_ADDRESS
              value: gnnameresolver:9999
          ports:
            - containerPort: 8888
              name: thrift-api
            - containerPort: 9990
              name: http-admin
