---
apiVersion: v1
kind: Service
metadata:
  name: gnmatcher-api
  namespace: gn
  labels:
    app: gnmatcher
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 9999
      name: thrift-api
      targetPort: 9999
    - port: 9990
      name: http-admin
      targetPort: 9990
  selector:
    app: gnmatcher
    tier: frontend
    type: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnmatcher-api
  namespace: gn
spec:
  replicas: 5
  template:
    metadata:
      name: gnmatcher-api
      labels:
        app: gnmatcher
        tier: frontend
        type: api
    spec:
      containers:
        - name: gnmatcher
          image: gnames/gnindex-debug:gnmatcher-0.1.0-20180425_1550_CDT-SNAPSHOT
          ports:
            - containerPort: 9999
              name: thrift-api
            - containerPort: 9990
              name: http-admin
          readinessProbe:
            httpGet:
              path: /admin/ping
              port: 9990
            initialDelaySeconds: 30
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /admin/ping
              port: 9990
            initialDelaySeconds: 300
            timeoutSeconds: 3
