---
apiVersion: v1
kind: Service
metadata:
  name: gnnamefilter
  namespace: gn
  labels:
    app: gnnamefilter
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 9999
      name: thrift-api
      targetPort: 9999
    - port: 9990
      name: http-admin
      targetPort: 9990
  selector:
    app: gnnamefilter
    tier: frontend
    type: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnnamefilter
  namespace: gn
spec:
  replicas: 10
  template:
    metadata:
      name: gnnamefilter
      labels:
        app: gnnamefilter
        tier: frontend
        type: api
    spec:
      containers:
        - name: gnnamefilter
          image: gnames/gnindex-debug:gnnamefilter-0.1.0-20171213_1311_CST-SNAPSHOT
          ports:
            - containerPort: 9999
              name: thrift-api
            - containerPort: 9990
              name: http-admin
          readinessProbe:
            httpGet:
              path: /admin/ping
              port: 9990
            initialDelaySeconds: 15
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /admin/ping
              port: 9990
            initialDelaySeconds: 300
            timeoutSeconds: 3
          env:
            - name: MATCHER_ADDRESS
              value: gnmatcher-api:9999
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: gnindex
                  key: db.host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: gnindex
                  key: db.port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: gnindex
                  key: db.database
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gnindex
                  key: db.user
            - name: DB_USER_PASS
              valueFrom:
                secretKeyRef:
                  name: gnindex
                  key: db.user.password
