---
apiVersion: v1
kind: Service
metadata:
  name: gnindex-db-slave2-service
  namespace: gn
  labels:
    app: gnindex
    tier: backend
    type: slave
    node: "3"
spec:
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: gnindex
    tier: backend
    type: slave
    node: "3"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnindex-db-slave2
  namespace: gn
spec:
  replicas: 1
  template:
    metadata:
      name: gresolver-db-slave2
      labels:
        app: gnindex
        tier: backend
        type: slave
        node: "3"
    spec:
      volumes:
        - name: gnindex-db-slave-vol
          emptyDir: {}
      containers:
        -
          name: gnindex-db-slave2
          image: paunin/postgresql-cluster-pgsql
          env: # those variables are not secret as it's just initial state of DB
            -
              name: "REPLICATION_PRIMARY_HOST"
              value: "gnindex-db-master-service"
            -
              name: "NODE_ID"
              value: "3"
            -
              name: "NODE_NAME"
              value: "node3"
            -
              name: "CLUSTER_NODE_NETWORK_NAME"
              value: "gnindex-db-slave2-service"
            -
              name: "REPMGR_WAIT_POSTGRES_START_TIMEOUT"
              valueFrom:
                configMapKeyRef:
                  name: gnindex
                  key: db.repmgr.timeout

            # Cluster configs
            - name: "CLUSTER_NAME"
              valueFrom:
                configMapKeyRef:
                  name: gnindex
                  key: db.cluster.name
            - name: "REPLICATION_DB"
              valueFrom:
                configMapKeyRef:
                  name: gnindex
                  key: db.cluster.replication.db
            - name: "REPLICATION_USER"
              valueFrom:
                secretKeyRef:
                  name: gnindex
                  key: db.cluster.replication.user
            - name: "REPLICATION_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: gnindex
                  key: db.cluster.replication.user.password
          ports:
            -
              containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: gnindex-db-slave-vol
