---
apiVersion: v1
kind: Service
metadata:
  name: gnindex-pgpool
  namespace: gn
  labels:
    app: gnindex
    tier: backend
    type: load-balancer
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30111
  selector:
    app: gnindex
    tier: backend
    type: load-balancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gnindex-pgpool
  namespace: gn
  labels:
    app: gnindex
    tier: backend
    type: load-balancer
spec:
  replicas: 2
  template:
    metadata:
      name: database-pgpool
      labels:
        app: gnindex
        tier: backend
        type: load-balancer
    spec:
      containers:
      - name: database-pgpool
        image: paunin/postgresql-cluster-pgpool
        ports:
          - containerPort: 5432
        env:
          # pcp
          - name: "PCP_USER"
            valueFrom:
              secretKeyRef:
                name: gnindex
                key: db.pool.pcp.user
          - name: "PCP_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: gnindex
                key: db.pool.pcp.password

          # Cluster configs  to hearbit checks
          - name: "CHECK_USER"
            valueFrom:
              secretKeyRef:
                name: gnindex
                key: db.cluster.replication.user
          - name: "CHECK_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: gnindex
                key: db.cluster.replication.user.password
          - name: "DB_USERS"
            valueFrom:
              secretKeyRef:
                name: gnindex
                key: db.pool.users
          - name: "BACKENDS"
            valueFrom:
              configMapKeyRef:
                name: gnindex
                key: db.pool.backends
