kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gnindex-pvc
  namespace: gn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
  selector:
    matchLabels:
      app: gnindex
      tier: backend
      type: master
      node: "1"
