
source 'https://rubygems.org'

gem 'actionpack', '~> 6.1'
gem 'activerecord', '~> 6.1'
gem 'pg', '~> 0.18'
gem 'sinatra-activerecord', '~> 2.0'

group :development do
  gem 'byebug', '~> 8.2'
end

group :test do
  gem 'rake', '~> 11.1'
end
